// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import CatController from "./cat_controller.js"
application.register("cat", CatController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
