version: '3'

services:

  _build: &image
    command: ['echo', 'build completed']
    build:
      context: .
      dockerfile: Dockerfile.dev

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my_password

  app:
    <<: *image
    command: ./script/start
    tty: true
    volumes:
      - .:/workspace:cached
      - bundler:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - RAILS_MAX_THREADS=5
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_SIDEKIQ_URL=redis://redis:6379/0
      - REDIS_CABLE_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/2
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=my_password
    depends_on:
      - _build
      - db
      - redis
    tmpfs:
      - /tmp

  # esbuild:
  #   <<: *image
  #   command: ./script/esbuild
  #   tty: true
  #   volumes:
  #     - .:/workspace
  #     - bundler:/usr/local/bundle
  #   depends_on:
  #     - _build

  redis:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis/data
    # ports:
    #   - 6379:6379

volumes:
  bundler:
  db-data:
  redis-data:
